from __future__ import annotations

from enum import Enum


class StringEnum(str, Enum):
    def __str__(self) -> str:
        return self.value


class AniListStatus(StringEnum):
    NOT_YET_RELEASED = "NOT_YET_RELEASED"
    RELEASING = "RELEASING"
    FINISHED = "FINISHED"
    CANCELLED = "CANCELLED"
    HIATUS = "HIATUS"
    UNKNOWN = "UNKNOWN"


class TrackerWorkflowStatus(StringEnum):
    UPCOMING = "UPCOMING"
    CURRENTLY_AIRING = "CURRENTLY_AIRING"
    FINISHED_READY_TO_ADD = "FINISHED_READY_TO_ADD"
    MOVIE_THEATRICAL_ONLY = "MOVIE_THEATRICAL_ONLY"
    MOVIE_DIGITALLY_AVAILABLE = "MOVIE_DIGITALLY_AVAILABLE"
    ON_SERVER = "ON_SERVER"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    ARCHIVED = "ARCHIVED"


class ServerPresence(StringEnum):
    NOT_FOUND = "NOT_FOUND"
    PARTIAL = "PARTIAL"
    COMPLETE = "COMPLETE"
    UNKNOWN_COVERAGE = "UNKNOWN_COVERAGE"
    PATH_MISSING = "PATH_MISSING"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class ReviewStatus(StringEnum):
    NONE = "NONE"
    AMBIGUOUS_MATCH = "AMBIGUOUS_MATCH"
    CONFLICTING_MATCHES = "CONFLICTING_MATCHES"
    MISSING_CONFIRMED_PATH = "MISSING_CONFIRMED_PATH"
    IDENTITY_CONFLICT = "IDENTITY_CONFLICT"
    SEASON_MAPPING_REQUIRED = "SEASON_MAPPING_REQUIRED"
    EPISODE_MAPPING_REQUIRED = "EPISODE_MAPPING_REQUIRED"
    SPECIAL_MAPPING_REQUIRED = "SPECIAL_MAPPING_REQUIRED"
    LEGACY_DATA_REVIEW = "LEGACY_DATA_REVIEW"
    MANUAL_REVIEW = "MANUAL_REVIEW"


class MediaKind(StringEnum):
    TV = "TV"
    TV_SHORT = "TV_SHORT"
    MOVIE = "MOVIE"
    OVA = "OVA"
    ONA = "ONA"
    SPECIAL = "SPECIAL"
    MUSIC = "MUSIC"
    UNKNOWN = "UNKNOWN"


class TrackingContentKind(StringEnum):
    SERIES = "SERIES"
    SEASON = "SEASON"
    MOVIE = "MOVIE"
    SPECIAL = "SPECIAL"
    OVA = "OVA"
    ONA = "ONA"
    FRANCHISE_ENTRY = "FRANCHISE_ENTRY"
    UNKNOWN = "UNKNOWN"


class CoverageSource(StringEnum):
    FILESYSTEM = "FILESYSTEM"
    JELLYFIN_API = "JELLYFIN_API"
    MANUAL = "MANUAL"
    LEGACY = "LEGACY"
    UNKNOWN = "UNKNOWN"


class ConfidenceLevel(StringEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CONFIRMED = "CONFIRMED"
    UNKNOWN = "UNKNOWN"


class LibraryKind(StringEnum):
    TV = "TV"
    MOVIE = "MOVIE"
    UNKNOWN = "UNKNOWN"


class MappingConfirmation(StringEnum):
    PROPOSED = "PROPOSED"
    AUTOMATIC = "AUTOMATIC"
    MANUAL = "MANUAL"
    LEGACY = "LEGACY"


class MappingSource(StringEnum):
    SCANNER = "SCANNER"
    USER = "USER"
    LEGACY = "LEGACY"
    IMPORT = "IMPORT"


class OverrideType(StringEnum):
    FORCE_WORKFLOW_STATUS = "FORCE_WORKFLOW_STATUS"
    FORCE_SERVER_PRESENCE = "FORCE_SERVER_PRESENCE"
    FORCE_JELLYFIN_FOLDER = "FORCE_JELLYFIN_FOLDER"
    FORCE_JELLYFIN_SEASON = "FORCE_JELLYFIN_SEASON"
    FORCE_CONTENT_KIND = "FORCE_CONTENT_KIND"
    SUPPRESS_AUTOMATIC_MATCHING = "SUPPRESS_AUTOMATIC_MATCHING"
    SUPPRESS_NOTIFICATION_TYPE = "SUPPRESS_NOTIFICATION_TYPE"
    MARK_MAPPING_CONFIRMED = "MARK_MAPPING_CONFIRMED"
    CLEAR_MAPPING = "CLEAR_MAPPING"
    ARCHIVE_ENTRY = "ARCHIVE_ENTRY"
    RESTORE_ARCHIVED_ENTRY = "RESTORE_ARCHIVED_ENTRY"


class OverrideSource(StringEnum):
    USER = "USER"
    LEGACY = "LEGACY"
    IMPORT = "IMPORT"


class RejectionScope(StringEnum):
    EXACT_PATH = "EXACT_PATH"
    LIBRARY_ITEM = "LIBRARY_ITEM"
    CANDIDATE = "CANDIDATE"
    SUPPRESS_AUTOMATIC_MATCHING = "SUPPRESS_AUTOMATIC_MATCHING"


class RelationType(StringEnum):
    PREQUEL = "PREQUEL"
    SEQUEL = "SEQUEL"
    SIDE_STORY = "SIDE_STORY"
    PARENT = "PARENT"
    SPIN_OFF = "SPIN_OFF"
    ALTERNATIVE = "ALTERNATIVE"
    SUMMARY = "SUMMARY"
    CHARACTER = "CHARACTER"
    OTHER = "OTHER"
    MOVIE = "MOVIE"
    OVA = "OVA"
    ONA = "ONA"
    SPECIAL = "SPECIAL"


class RelationDirection(StringEnum):
    OUTBOUND = "OUTBOUND"
    INBOUND = "INBOUND"


class TransitionEventType(StringEnum):
    TRACKING_STARTED = "TRACKING_STARTED"
    MOVED_TO_UPCOMING = "MOVED_TO_UPCOMING"
    STARTED_AIRING = "STARTED_AIRING"
    NEW_EPISODE_AIRED = "NEW_EPISODE_AIRED"
    COVERAGE_BECAME_PARTIAL = "COVERAGE_BECAME_PARTIAL"
    COVERAGE_BECAME_COMPLETE = "COVERAGE_BECAME_COMPLETE"
    COVERAGE_LOST = "COVERAGE_LOST"
    SERIES_FINISHED = "SERIES_FINISHED"
    MOVIE_BECAME_THEATRICAL = "MOVIE_BECAME_THEATRICAL"
    MOVIE_BECAME_DIGITAL = "MOVIE_BECAME_DIGITAL"
    FOUND_ON_SERVER = "FOUND_ON_SERVER"
    NO_LONGER_FOUND_ON_SERVER = "NO_LONGER_FOUND_ON_SERVER"
    MAPPING_CHANGED = "MAPPING_CHANGED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    REVIEW_RESOLVED = "REVIEW_RESOLVED"
    ARCHIVED = "ARCHIVED"
    RESTORED = "RESTORED"
