from __future__ import annotations

from enum import Enum


class StringEnum(str, Enum):
    def __str__(self) -> str:
        return self.value


class ChannelPurpose(StringEnum):
    PRIVATE_TRACKER = "PRIVATE_TRACKER"
    SHARED_ANNOUNCEMENT = "SHARED_ANNOUNCEMENT"
    WINDOWS_LOCAL = "WINDOWS_LOCAL"


class OutboxStatus(StringEnum):
    PENDING = "PENDING"
    CLAIMED = "CLAIMED"
    DELIVERED = "DELIVERED"
    RETRY_WAIT = "RETRY_WAIT"
    FAILED_PERMANENT = "FAILED_PERMANENT"
    CANCELED = "CANCELED"
    SUPPRESSED = "SUPPRESSED"
    EXPIRED = "EXPIRED"


class DeliveryResultType(StringEnum):
    DELIVERED = "DELIVERED"
    RETRYABLE_FAILURE = "RETRYABLE_FAILURE"
    PERMANENT_FAILURE = "PERMANENT_FAILURE"
    CANCELED = "CANCELED"


class Severity(StringEnum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"


class PrivacyLevel(StringEnum):
    PRIVATE = "PRIVATE"
    SHARED_SAFE = "SHARED_SAFE"


class MentionPolicy(StringEnum):
    NONE = "NONE"
    EXPLICIT = "EXPLICIT"


class BatchHealth(StringEnum):
    SUCCESS = "SUCCESS"
    PARTIAL_SUCCESS = "PARTIAL_SUCCESS"
    FAILED = "FAILED"
    NO_WORK = "NO_WORK"


class EventType(StringEnum):
    TRACKING_STARTED = "TRACKING_STARTED"
    STARTED_AIRING = "STARTED_AIRING"
    NEW_EPISODE_AIRED = "NEW_EPISODE_AIRED"
    NEXT_EPISODE_SCHEDULED = "NEXT_EPISODE_SCHEDULED"
    AIRING_TIME_CHANGED = "AIRING_TIME_CHANGED"
    EPISODE_DELAYED = "EPISODE_DELAYED"
    AIRING_SCHEDULE_REMOVED = "AIRING_SCHEDULE_REMOVED"
    SERIES_FINISHED_AIRING = "SERIES_FINISHED_AIRING"
    SERIES_STATUS_CHANGED = "SERIES_STATUS_CHANGED"
    PROVIDER_REFRESH_PARTIAL_FAILURE = "PROVIDER_REFRESH_PARTIAL_FAILURE"
    PROVIDER_REFRESH_RECOVERED = "PROVIDER_REFRESH_RECOVERED"
    FOUND_ON_SERVER = "FOUND_ON_SERVER"
    COVERAGE_BECAME_PARTIAL = "COVERAGE_BECAME_PARTIAL"
    COVERAGE_BECAME_COMPLETE = "COVERAGE_BECAME_COMPLETE"
    COVERAGE_LOST = "COVERAGE_LOST"
    MISSING_AIRED_EPISODES = "MISSING_AIRED_EPISODES"
    CONFIRMED_PATH_MISSING = "CONFIRMED_PATH_MISSING"
    SERVER_MAPPING_CHANGED = "SERVER_MAPPING_CHANGED"
    MOVIE_THEATRICAL_RELEASED = "MOVIE_THEATRICAL_RELEASED"
    MOVIE_BECAME_DIGITALLY_AVAILABLE = "MOVIE_BECAME_DIGITALLY_AVAILABLE"
    MOVIE_FOUND_ON_SERVER = "MOVIE_FOUND_ON_SERVER"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    REVIEW_RESOLVED = "REVIEW_RESOLVED"
    MAPPING_CONFIRMED = "MAPPING_CONFIRMED"
    MAPPING_REJECTED = "MAPPING_REJECTED"
    TRACKED_ENTRY_ARCHIVED = "TRACKED_ENTRY_ARCHIVED"
    TRACKED_ENTRY_RESTORED = "TRACKED_ENTRY_RESTORED"
    DAILY_SUMMARY = "DAILY_SUMMARY"
    WEEKLY_AIRING_SUMMARY = "WEEKLY_AIRING_SUMMARY"
    WEEKLY_SERVER_SUMMARY = "WEEKLY_SERVER_SUMMARY"
    SHARED_EPISODES_AVAILABLE = "SHARED_EPISODES_AVAILABLE"
    SHARED_SEASON_COMPLETE = "SHARED_SEASON_COMPLETE"
    SHARED_SERIES_AVAILABLE = "SHARED_SERIES_AVAILABLE"
